#!/usr/bin/env bash
# Rebuild schema.sql from tables/, storage/, and functions/. Run from repo root or this directory.
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/schema.sql"

{
  cat <<'EOF'
-- =============================================================================
-- MapMe Route Optimizer — Supabase bootstrap (paste entire file in SQL Editor).
--
-- AUTO-GENERATED by supabase/build-schema.sh from:
--   tables/saved_trips.sql
--   storage/avatars_bucket.sql
--   functions/list_saved_trips_page.sql
--
-- Apply order: table → storage → function (RPC reads saved_trips).
-- =============================================================================

EOF
  echo "-- === BEGIN tables/saved_trips.sql ==="
  echo
  cat "$DIR/tables/saved_trips.sql"
  echo
  echo "-- === END tables/saved_trips.sql ==="
  echo "-- === BEGIN storage/avatars_bucket.sql ==="
  echo
  cat "$DIR/storage/avatars_bucket.sql"
  echo
  echo "-- === END storage/avatars_bucket.sql ==="
  echo "-- === BEGIN functions/list_saved_trips_page.sql ==="
  echo
  cat "$DIR/functions/list_saved_trips_page.sql"
  echo
  echo "-- === END functions/list_saved_trips_page.sql ==="
} >"$OUT"

echo "Wrote $OUT"
