-- =============================================================================
-- MapMe Route Optimizer — Supabase bootstrap (paste entire file in SQL Editor).
--
-- AUTO-GENERATED by supabase/build-schema.sh from:
--   tables/saved_trips.sql
--   storage/avatars_bucket.sql
--   functions/list_saved_trips_page.sql
--
-- Apply order: table → storage → function (RPC reads saved_trips).
-- =============================================================================

-- === BEGIN tables/saved_trips.sql ===

-- public.saved_trips — per-user saved route payloads (OptimizeResponse JSON).
-- Depends: auth.users (Supabase Auth, already present).

create table if not exists public.saved_trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists saved_trips_user_created_at_idx
  on public.saved_trips (user_id, created_at desc);

alter table public.saved_trips
  add column if not exists is_favorite boolean not null default false;

create index if not exists saved_trips_user_favorite_idx
  on public.saved_trips (user_id, is_favorite)
  where is_favorite = true;

alter table public.saved_trips enable row level security;

create policy "saved_trips_select_own"
  on public.saved_trips for select
  using (auth.uid() = user_id);

create policy "saved_trips_insert_own"
  on public.saved_trips for insert
  with check (auth.uid() = user_id);

create policy "saved_trips_update_own"
  on public.saved_trips for update
  using (auth.uid() = user_id);

create policy "saved_trips_delete_own"
  on public.saved_trips for delete
  using (auth.uid() = user_id);

-- === END tables/saved_trips.sql ===
-- === BEGIN storage/avatars_bucket.sql ===

-- Storage bucket + policies for profile photo and cover (not a public schema table).
-- Run after Storage is enabled on the project.
-- Default bucket name matches frontend VITE_AVATAR_BUCKET (default: avatars).
-- Objects must live under {auth.uid()}/... e.g. {uuid}/avatar and {uuid}/profile-banner.

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatars_public_read" on storage.objects;
drop policy if exists "avatars_insert_own" on storage.objects;
drop policy if exists "avatars_update_own" on storage.objects;
drop policy if exists "avatars_delete_own" on storage.objects;

create policy "avatars_public_read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatars_insert_own"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and split_part(name, '/', 1) = auth.uid()::text
  );

create policy "avatars_update_own"
  on storage.objects for update
  using (
    bucket_id = 'avatars'
    and split_part(name, '/', 1) = auth.uid()::text
  );

create policy "avatars_delete_own"
  on storage.objects for delete
  using (
    bucket_id = 'avatars'
    and split_part(name, '/', 1) = auth.uid()::text
  );

-- === END storage/avatars_bucket.sql ===
-- === BEGIN functions/list_saved_trips_page.sql ===

-- Paginated History list + server-side search. Depends: public.saved_trips.
-- Returns { "total_count": <bigint>, "rows": [ ... ] }.

create or replace function public.list_saved_trips_page(
  p_limit integer default 20,
  p_offset integer default 0,
  p_search text default null,
  p_saved_only boolean default false,
  p_transport_mode text default null,
  p_newest_first boolean default true
)
returns json
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  v_limit int := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset int := greatest(coalesce(p_offset, 0), 0);
  v_search text := nullif(trim(coalesce(p_search, '')), '');
  v_mode text := null;
  v_total bigint;
  v_rows json;
begin
  if p_transport_mode is not null and lower(p_transport_mode) in ('driving', 'walking', 'transit') then
    v_mode := lower(p_transport_mode);
  end if;

  select count(*)::bigint
  into v_total
  from public.saved_trips t
  where auth.uid() = t.user_id
    and (not p_saved_only or t.is_favorite)
    and (
      v_mode is null
      or coalesce(t.payload ->> 'transport_mode', 'driving') = v_mode
    )
    and (
      v_search is null
      or strpos(lower(coalesce(t.title, '')), lower(v_search)) > 0
      or strpos(lower(coalesce(t.payload ->> 'origin_query', '')), lower(v_search)) > 0
      or strpos(lower(coalesce(t.payload ->> 'origin_address', '')), lower(v_search)) > 0
      or exists (
        select 1
        from jsonb_array_elements(coalesce(t.payload -> 'stops_resolved', '[]'::jsonb)) as s
        where strpos(lower(coalesce(s ->> 'query', '')), lower(v_search)) > 0
           or strpos(lower(coalesce(s ->> 'address', '')), lower(v_search)) > 0
      )
    );

  if p_newest_first then
    select coalesce(
      (
        select json_agg(row_to_json(sub))
        from (
          select t.id, t.user_id, t.title, t.payload, t.created_at, t.is_favorite
          from public.saved_trips t
          where auth.uid() = t.user_id
            and (not p_saved_only or t.is_favorite)
            and (
              v_mode is null
              or coalesce(t.payload ->> 'transport_mode', 'driving') = v_mode
            )
            and (
              v_search is null
              or strpos(lower(coalesce(t.title, '')), lower(v_search)) > 0
              or strpos(lower(coalesce(t.payload ->> 'origin_query', '')), lower(v_search)) > 0
              or strpos(lower(coalesce(t.payload ->> 'origin_address', '')), lower(v_search)) > 0
              or exists (
                select 1
                from jsonb_array_elements(coalesce(t.payload -> 'stops_resolved', '[]'::jsonb)) as s
                where strpos(lower(coalesce(s ->> 'query', '')), lower(v_search)) > 0
                   or strpos(lower(coalesce(s ->> 'address', '')), lower(v_search)) > 0
              )
            )
          order by t.created_at desc
          limit v_limit
          offset v_offset
        ) sub
      ),
      '[]'::json
    )
    into v_rows;
  else
    select coalesce(
      (
        select json_agg(row_to_json(sub))
        from (
          select t.id, t.user_id, t.title, t.payload, t.created_at, t.is_favorite
          from public.saved_trips t
          where auth.uid() = t.user_id
            and (not p_saved_only or t.is_favorite)
            and (
              v_mode is null
              or coalesce(t.payload ->> 'transport_mode', 'driving') = v_mode
            )
            and (
              v_search is null
              or strpos(lower(coalesce(t.title, '')), lower(v_search)) > 0
              or strpos(lower(coalesce(t.payload ->> 'origin_query', '')), lower(v_search)) > 0
              or strpos(lower(coalesce(t.payload ->> 'origin_address', '')), lower(v_search)) > 0
              or exists (
                select 1
                from jsonb_array_elements(coalesce(t.payload -> 'stops_resolved', '[]'::jsonb)) as s
                where strpos(lower(coalesce(s ->> 'query', '')), lower(v_search)) > 0
                   or strpos(lower(coalesce(s ->> 'address', '')), lower(v_search)) > 0
              )
            )
          order by t.created_at asc
          limit v_limit
          offset v_offset
        ) sub
      ),
      '[]'::json
    )
    into v_rows;
  end if;

  return json_build_object('total_count', v_total, 'rows', v_rows);
end;
$$;

grant execute on function public.list_saved_trips_page(
  integer, integer, text, boolean, text, boolean
) to authenticated;

grant execute on function public.list_saved_trips_page(
  integer, integer, text, boolean, text, boolean
) to service_role;

-- === END functions/list_saved_trips_page.sql ===
